### ISSUE TITLE
Subscribing to a users published playlist

### ISSUE THREAD

**Issue by bradleyjones** [Hexxeh/spotify-websocket-api#30]
When I subscribe to a specific users playlist through the spotify desktop client then call list in respotify I see the following error:

Playlists

 [1] Starred
Traceback (most recent call last):
  File "respotify.py", line 285, in <module>
    command_loop()
  File "respotify.py", line 251, in command_loop
    command_map[command_name][0](command[1:])
  File "respotify.py", line 91, in command_list
    print " ["+str(index)+"] "+playlist.getName()
  File "../../spotify_web/friendly.py", line 254, in getName
    return "Starred" if self.getID() == "starred" else self.obj.attributes.name
AttributeError: 'bool' object has no attribute 'attributes'
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 505, in run
  File "../../spotify_web/spotify.py", line 740, in heartbeat_handler
  File "../../spotify_web/spotify.py", line 594, in heartbeat
  File "../../spotify_web/spotify.py", line 643, in send_command
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

However if I unsubscribe and then call list it shows me my playlists as expected despite a number of them being playlists I am subscribed to (e.g. Digster playlists) not sure if this is a bug or one of the yet unimplemented social features?

Thanks for any help in advance

**Comment by Hexxeh** [comment]
Sounds like a temporarily failure (occasionally we get an error from
Spotify where the API just returns False denoting you should try the
request again). This isn't handled everywhere it should be.
