### ISSUE TITLE
Problem with authenticating to run test.py, but blocker.py works?

### ISSUE THREAD

**Issue by niftylettuce** [Hexxeh/spotify-websocket-api#55]
I get the following error when I run:

``` bash
USERNAME=myusername PASSWORD=mypassword python test.py
```

Output:

``` bash
[ERROR] There was a problem authenticating, authentication failed
Login failed
E[ERROR] There was a problem authenticating, authentication failed
Login failed
E
======================================================================
ERROR: test_get_track_by_uri (__main__.SpotifyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 36, in test_get_track_by_uri
    self.assertEqual(reference["title"], track.getName())
AttributeError: 'bool' object has no attribute 'getName'

======================================================================
ERROR: test_playlist_add_delete (__main__.SpotifyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 42, in test_playlist_add_delete
    before = len(self.spotify.getPlaylists())
  File "/media/nexus/Data/Public/test-project/python/spotify-websocket-api/spotify_web/friendly.py", line 42, in __call__
    res = cache[key] = self.func(*args, **kw)
  File "/media/nexus/Data/Public/test-project/python/spotify-websocket-api/spotify_web/friendly.py", line 449, in getPlaylists
    playlist_uris += ["spotify:user:"+username+":starred"]
TypeError: cannot concatenate 'str' and 'NoneType' objects

----------------------------------------------------------------------
Ran 2 tests in 2.921s

FAILED (errors=2)
```

However I can run blocker just fine...

``` bash
cd examples
python blocking.py myusername mypassword track
```

Output:

``` bash
Cross the Line
```

**Comment by niftylettuce** [comment]
Is this somehow related to https://github.com/TooTallNate/node-spotify-web/pull/85?  Any insight as to why that issue on the node project isn't working?
