### ISSUE TITLE
Respotify fails to start

### ISSUE THREAD

**Issue by Thalhammer** [Hexxeh/spotify-websocket-api#62]
It seems the main library is broken somehow.
Running ./respotify results in this:
[NOTICE] Connecting to wss://lon2-linkap-a4.ap.spotify.com/
[NOTICE] Logging in
[DEBUG] sent {..... A lot of stuff.....}
[DEBUG] recv {"id":0,"result":"ok"}
[DEBUG] sent {"args":[],"name":"sp/user_info","id":"1"}
[DEBUG] recv {"message":["do_work","var t2; try{ var d=new Date(); t2=d[(35725129862..toString(36<<0))[0]];}catch(_) {};this.reply('' + t2);"]}
[DEBUG] Got do_work message, payload: var t2; try{ var d=new Date(); t2=d[(35725129862..toString(36<<0))[0]];}catch(_) {};this.reply('' + t2);
[DEBUG] sent {"args":["v1"],"name":"sp/work_done","id":"2"}
[DEBUG] recv {"message":["ping_flash2","90 177 209 213 40 76 89 196 90 9 254 253 7 248 109 220 81 91 1 85"]}
[DEBUG] Sending pong 200 38 246 72 76 145 84 44 143 73
[DEBUG] sent {"args":["200 38 246 72 76 145 84 44 143 73"],"name":"sp/pong_flash2","id":"3"}
[DEBUG] recv {"id":2,"result":"ok"}
[DEBUG] Got ack for message reply
Traceback (most recent call last):
  File "./respotify.py", line 277, in <module>
    spotify = Spotify(args.username, args.password)
  File "../../spotify_web/friendly.py", line 619, in **init**
    self.tunigo = Tunigo(region=self.api.country)
  File "../../spotify_web/tunigoapi.py", line 14, in **init**
    Logging.debug("Starting with Tunigo for region: "  + self.region)
TypeError: cannot concatenate 'str' and 'NoneType' objects

Running ./blocking.py :
.....
[DEBUG] Got ack for message reply
Traceback (most recent call last):
  File "./blocking.py", line 40, in <module>
    print album.name+" - "+album.artist[0].name+"\n"
AttributeError: 'bool' object has no attribute 'name'

All the other examples fail too.

Sincerly,
Dominik Thalhammer

**Comment by keshavdv** [comment]
+1

**Comment by vmattos** [comment]
The same is happeing to me

**Comment by tsmithe** [comment]
Also here

**Comment by williamtdr** [comment]
+1

**Comment by TunaLobster** [comment]
Also seeing this issue. Seems to be an issue with the region attribute

EDIT: Fixed by changing all occurrences except on line 12 of tunigoapi.py to "us" with quotes.
